version: '1'

services:
  main_server:
    build: ./
    container_name: upload_file_to_s3
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_DEBUG=True
      - S3_ACCESS_KEY=AKIAWIT4NZP73XJEXWU4
      - S3_SECRET_KEY=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
      - S3_BUCKET_NAME=globalstoragebuh
    mem_limit: 512m
    storage_opt:
      size: 512M
  