version: '1'

services:
  main_server:
    build: ./
    container_name: upload_file_to_s3
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_DEBUG=True
      - S3_ACCESS_KEY=YOUR_ACCESS_KEY
      - S3_SECRET_KEY=YOUR_SECRET_KEY
      - S3_BUCKET_NAME=YOUR_BUCKET_NAME
    mem_limit: 512m
    storage_opt:
      size: 512M
  